name: rentacar_spa
description: A web server application.
version: 0.0.1
author: asdas

environment:
  sdk: '>=1.24.1 <2.0.0'

dependencies:
  analyzer: '>=0.29.10 <0.31.0'
  aqueduct: "any"
  angular: ^4.0.0
  angular_router: ^1.0.2
  http: ^0.11.0
  angular_components: ^0.7.0
  angular_forms: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  webdriver: ^1.2.1

transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
# - angular:
#     entry_points:
#       - web/main.dart
#     resolved_identifiers:
#         BrowserClient: 'package:http/browser_client.dart'
#         Client: 'package:http/http.dart'
# - angular/transform/reflection_remover:
#     $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc